export const initialState = {
  events: {
    eventList: [
      {
        id: "event-1-2025-01-01",
        title: "Event1",
        date: "2025-01-01",
        time: "10:00",
        category: "Music",
        description: "A music event featuring local bands.",
      },
      {
        id: "event-2-2025-01-02",
        title: "Event2",
        date: "2025-01-02",
        time: "14:00",
        category: "Art",
        description: "An art exhibition showcasing contemporary works.",
      },
      {
        id: "event-3-2025-01-03",
        title: "Event3",
        date: "2025-01-03",
        time: "18:00",
        category: "Technology",
        description:
          "A tech talk about the latest trends in software development.",
      },
      {
        id: "event-4-2025-01-04",
        title: "Event4",
        date: "2025-01-04",
        time: "09:00",
        category: "Food",
        description: "A culinary workshop for food lovers.",
      },
      {
        id: "event-5-2025-01-05",
        title: "Event5",
        date: "2025-01-05",
        time: "15:00",
        category: "Education",
        description: "A seminar on modern teaching methods.",
      },
      {
        id: "event-6-2025-01-06",
        title: "Event6",
        date: "2025-01-06",
        time: "11:00",
        category: "Music",
        description: "A classical music performance by a local orchestra.",
      },
      {
        id: "event-7-2025-01-07",
        title: "Event7",
        date: "2025-01-07",
        time: "13:00",
        category: "Health",
        description: "A workshop on mindfulness and mental well-being.",
      },
      {
        id: "event-8-2025-01-08",
        title: "Event8",
        date: "2025-01-08",
        time: "16:00",
        category: "Technology",
        description: "A conference on AI and its impact on the future of work.",
      },
      {
        id: "event-9-2025-01-09",
        title: "Event9",
        date: "2025-01-09",
        time: "10:00",
        category: "Food",
        description: "A food festival with international cuisines.",
      },
      {
        id: "event-10-2025-01-10",
        title: "Event10",
        date: "2025-01-10",
        time: "17:00",
        category: "Art",
        description: "An art gallery tour showcasing modern sculptures.",
      },
    ],
    error: null,
    editEvent: false,
  },
  filter: {
    eventTitle: "",
    selectedCategory: "all",
    dateRange: {
      startDate: "",
      endDate: "",
    },
  },
  pages: {
    currentPage: 1,
    itemsPerPage: 4,
    totalItems: 0,
  },
};
